import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../../Components/Header'
const inter = Inter({ subsets: ['latin'] })
import { SocialIcon } from 'react-social-icons'
import Main from '../../Components/Main'
import Port from "../public/Port.png"
import About from '../../Components/About'
import Experince from '../../Components/Experince'
import Skills from '../../Components/Skills/Skills'
import Contact from '../../Components/Contact'
import Background from '../../Components/Background'

export default function Home() {
  return (
    <div className=" text-violet-950 h-screen snap-y snap-mandatory overflow-scroll z-0 no-scrollbar">
            <Head>
        <title>Ebyan Coding Site ✨</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://i.pinimg.com/originals/d0/b2/9b/d0b29bc0ecb3559d99595049e3c3356d.jpg" />
      </Head>

      <Header />

      <section id="main" className='snap-start'>
        <Main />
      </section>


      <section id='About' className='snap-center' >
        <About />
      </section>

      <section id='Experince' className='snap-center'>
        <Experince />
      </section>

      <section id='Skills' className='snap-start'>
        <Skills />
      </section>

      <section id="Contant" className='snap-start'> 
        <Contact/>
      </section>
    </div>
  )
}
